---
title: "Group and split the data"
author: "Anqi Dai"
date: "3/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(gridExtra)
```

```{r}
# download the data to local first so that I can test
# spent a lot of time finally figuring this out 
# read the test data

Test <- read_csv('../data/testing_TE.csv') %>%
  mutate(localPath = str_replace_all(Path, '/projectnb/lau-bumc/qichengm/projects/Lau_lab/human/HD_PD_project/miRNA/','../data/allTest/')) %>%
  mutate(fileContent = map(localPath,  ~ read_tsv(., col_names = F, skip = 1))) %>%
  unnest %>%
  dplyr::select(-X1, -Path) %>%
  rename(bin = X2,  
         Pos1 = X3,
         Neg1 = X4,
         Pos2 = X5,
         Neg2 = X6,
         Pos3 = X7,
         Neg3 = X8) %>%
  mutate(Neg1 = abs(Neg1),
         Neg2 = abs(Neg2),
         Neg3 = abs(Neg3))

```

```{r}
# fake data loading
Test <- read_csv('../data/fake_data_real_format.csv') %>%
  mutate(Status = factor(Status))
```

```{r}

TEs <- names(table(Test$TE))
Nums <- seq(1,3)

input_params <- data_frame(
  TE_name = rep(TEs,each = 3),
  Num = rep(Nums, length(TEs))
)

DF <- Test
```

```{r}
# fake data plotting

TE_name <- 'TE_simulate'
Num <- 1

source('02_plot_a_single_boxplot_pair.R')
draw_per_bin_boxpot(TE_name, Num) + ggsave('../figs/000simulate_boxplot.jpg', width = 20, height = 12, dpi = 300)

source('01_plot_a_single_heatmap_pair.R')
draw_clustered_heatmap(TE_name, Num) + ggsave('../figs/000simulate_hm.jpg', width = 20, height = 12, dpi = 300)

source('03_plot_a_single_lineplot_pair.R')
draw_differential_line_plot(TE_name, Num) + ggsave('../figs/000simulate_line.jpg', width = 20, height = 12, dpi = 300)
```


```{r box}
# the boxplot
source('02_plot_a_single_boxplot_pair.R')

# my task: split a df to make a list of dfs and then map a function that needs 2 inputs on each small df.

# split the input to be a list of dfs
list_dfs <- input_params %>%
  split(factor(input_params$TE_name)) 

TE_names <- names(list_dfs)

# I need to have a list of two lists, each sub list has three ggplot object
ret <- lapply(TE_names , function(name) {
  pmap(list_dfs[[name]], function(TE_name, Num){
    draw_per_bin_boxpot(TE_name, Num)
  })
})

names(ret) <- TE_names

sapply(TE_names, function(name){
  ggsave(str_glue('../figs/{name}_boxplot.pdf'), arrangeGrob(ret[[name]][[1]],ret[[name]][[2]],ret[[name]][[3]], nrow = 3) ,  width = 20, height = 36, dpi = 300) 
})
```


```{r heatmap}
source('01_plot_a_single_heatmap_pair.R')

ret <- lapply(TE_names , function(name) {
  pmap(list_dfs[[name]], function(TE_name, Num){
    draw_clustered_heatmap(TE_name, Num)
  })
})

names(ret) <- TE_names

sapply(TE_names, function(name){
  ggsave(str_glue('../figs/{name}_heatmap.pdf'), arrangeGrob(ret[[name]][[1]],ret[[name]][[2]],ret[[name]][[3]], nrow = 3), width = 20, height = 72, dpi = 300, limitsize = FALSE) 
})
```


```{r lineplot}
source('03_plot_a_single_lineplot_pair.R')

# I need to have a list of two lists, each sub list has three ggplot object
ret <- lapply(TE_names , function(name) {
  pmap(list_dfs[[name]], function(TE_name, Num){
    draw_differential_line_plot(TE_name, Num)
  })
})

names(ret) <- TE_names

sapply(TE_names, function(name){
  ggsave(str_glue('../figs/{name}_lineplot.pdf'), arrangeGrob(ret[[name]][[1]],ret[[name]][[2]],ret[[name]][[3]], nrow = 3) ,  width = 20, height = 36, dpi = 300) 
})
```

