---
title: "Make metadata file for testing"
author: "Anqi Dai"
date: "3/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}
library(tidyverse)
```

```{r}
# load the table for testing on one TE
# select the two most abundant TE for testing 'ALU:1-312' and 'HERV49I:1-6331'
# and only use the control and HD now


ret <-list.files('../data/allTest/')

TEs <- c( 'TE@ALU:1-312', 'TE@L1HS:1-6064')
RET <- apply(expand.grid(ret, TEs), 1, paste, collapse="/")


res <- data_frame(folderName = RET) %>%
    separate(folderName, into = c('SampleFolder','TE'), sep = '/') %>%
    mutate(Path = str_glue('/projectnb/lau-bumc/qichengm/projects/Lau_lab/human/HD_PD_project/miRNA/{SampleFolder}/{TE}'))  %>%
    mutate(TE = str_replace_all(TE, '^TE@','')) %>%
    mutate(Status = if_else(grepl(pattern = '^C', SampleFolder), 'Control', if_else(grepl(pattern = '^P', SampleFolder), 'Parkinsons','Huntingtons'))) %>%
    mutate(Status = factor(Status))  %>%
    mutate(Sample = str_replace_all(SampleFolder, '_TE$','')) %>%
    filter(Status != 'Parkinsons') %>%
    dplyr::select(TE, Sample, Status, Path)
 
res %>%
  write_csv('../data/testing_TE.csv')


```

