---
title: "test_script"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(pheatmap)
library(ggpubr)
library(cowplot)
library(gridExtra)
```

## clustered heatmap

```{r}
# load the fake data
pos <- read_csv('../data/test_data_pos.csv') %>%
  column_to_rownames(var = 'bin') %>%
  as.matrix()

neg <- read_csv('../data/test_data_neg.csv') %>%
  column_to_rownames(var = 'bin') %>%
  as.matrix()


# get the max number of the two matrix that will be the max value for the two heatmaps
max_cnt <- max(max(pos), max(neg))
```

```{r colors}
colGradient <- function( cols, length, cmax=255 )
{ ramp <- colorRamp(cols)
rgb( ramp(seq(0,1,length=length)), max=cmax )
}

yellow <- colGradient(c("#EBEBF3","#4C3C90"),length=15) 

blue <- colGradient(c("#DAE8F5","#0B559F"),length=15) 

# Create a heatmap of your genes using the entire training set.
positive <- t(pos)
negative <- t(neg)

sample_names <- rownames(positive)

annot <- data_frame(
  Sample =sample_names, 
  Group = c(rep('Disease', length(sample_names[grepl(pattern = '^D', sample_names)])),
           rep('Control', length(sample_names[grepl(pattern = '^C', sample_names)])) )
  ) %>%
  mutate(Group = factor(Group))%>%
  column_to_rownames('Sample')

# the palette for the Group variable
annotCol <- list(Group = c('#42B440', '#EC0000'))
names(annotCol$Group) = c('Control','Disease')

# breaks : which set the limit of the count and color mapping relationship
breaks <- seq(0, max_cnt, length.out = 1+length(blue))

```

```{r} 
# for the positive strand
pheatmap(
  positive,
  color= blue, 
  breaks = breaks,
  annotation_row = annot,
  annotation_colors = annotCol,
  border_color = NA,
  treeheight_row = 100,
  angle_col = 45,
  show_rownames = TRUE,
  show_colnames = TRUE,
  height = 5,
  width = 25,
  cluster_rows = T,
  cluster_cols = F,
  filename = '../figs/pos_heatmap.jpg',
  main = 'Positive strand'
)


# for the negative strand
pheatmap(
  negative,
  color= yellow, 
  breaks = breaks,
  annotation_row = annot,
  annotation_colors = annotCol,
  border_color = NA,
  treeheight_row = 100,
  angle_col = 45,
  show_rownames = TRUE,
  show_colnames = TRUE,
  height = 5,
  width = 25,
  cluster_rows = T,
  cluster_cols = F,
  filename = '../figs/neg_heatmap.jpg',
  main = 'Negative strand'
)
```

## Per-bin boxplots

```{r}
# format the counts table to be in a long format

box_pos <- positive %>%
  as_tibble %>%
  rename_all(
    funs(paste0('b',.))
  ) %>%
  gather(key = bin , value = cnt, b0:b99)

box_neg <-  negative %>%
  as_tibble %>%
  rename_all(
    funs(paste0('b',.))
  ) %>%
  gather(key = bin , value = cnt, b0:b99)
```


```{r}
# plot the TPM of each bin as a box plot. the y limit should be 0 to max count too

# the postitive strand
ggboxplot(box_pos, x = 'bin', y = 'cnt',
          ggtheme = theme_minimal(),
          color = '#00468B',
          xlab = 'Bin', ylab = 'Positive'
                     )  +
  ylim(0, max_cnt) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggsave('../figs/boxplot_postive.jpg', width = 20, height = 5, dpi = 300)

# the negative strand
ggboxplot(box_neg, x = 'bin', y = 'cnt',
          ggtheme = theme_minimal(),
          color = '#00468B',
          xlab = 'Bin', ylab = 'Negative'
                     )  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_reverse()  + 
   ylim(max_cnt, 0) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  ggsave('../figs/boxplot_negative.jpg', width = 20, height = 5, dpi = 300)

```

